<a href="https://colab.research.google.com/github/zaur-guliyev/deep_learning/blob/main/Neural_Networks_and_Deep_Learning_Course_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time


In [2]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic =time.time()
c=np.dot(a,b)
toc =time.time()
print(c)
print(toc)
print(tic)
print(f"Vector = {toc-tic} ms")

c=0
tic =time.time()
for i in range(1000000):
  c+=a[i]*b[i]
toc =time.time()
print(f"Loop = {toc-tic} ms")
print(c)

249830.3263067567
1618933824.3230784
1618933824.321326
Vector = 0.0017523765563964844 ms
Loop = 0.7013182640075684 ms
249830.32630675394


In [3]:
ab=np.array([1,2])
cd=np.array([6,7])

df=np.dot(ab,cd)
df

20

In [4]:
list1=[1,2,4]
list2=[2,3,4]

re=0
for i in range(0,3):
  re+=list1[i]*list2[i]
  print(re)
print(re)

2
8
24
24


In [5]:
A=np.array([[56,0,4.4,8],
           [1.2, 104, 52,8],
           [1.8,135, 99, 0.9]])
A

array([[ 56. ,   0. ,   4.4,   8. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [6]:
cal=A.sum(axis=0)
cal.shape

(4,)

In [7]:
per=100*A/cal.reshape(1,4)
per

array([[94.91525424,  0.        ,  2.83140283, 47.33727811],
       [ 2.03389831, 43.51464435, 33.46203346, 47.33727811],
       [ 3.05084746, 56.48535565, 63.70656371,  5.32544379]])

In [8]:
a=np.random.rand(5)
a

array([0.34534253, 0.45093155, 0.77800138, 0.80095418, 0.55703853])

In [9]:
a.T

array([0.34534253, 0.45093155, 0.77800138, 0.80095418, 0.55703853])

In [10]:
a.reshape(1,5).T

array([[0.34534253],
       [0.45093155],
       [0.77800138],
       [0.80095418],
       [0.55703853]])

In [11]:
a=np.random.rand(5,1)
a

array([[0.75525754],
       [0.66651553],
       [0.55193419],
       [0.8570923 ],
       [0.18404719]])

In [12]:
np.dot(a,a.T)

array([[0.57041395, 0.50339088, 0.41685246, 0.64732542, 0.13900303],
       [0.50339088, 0.44424295, 0.36787271, 0.57126533, 0.12267031],
       [0.41685246, 0.36787271, 0.30463135, 0.47305854, 0.10158194],
       [0.64732542, 0.57126533, 0.47305854, 0.73460721, 0.15774543],
       [0.13900303, 0.12267031, 0.10158194, 0.15774543, 0.03387337]])

In [13]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [14]:
print(a)
print(b)
print(c)

[[ 0.76147453 -1.15478314 -0.4832127 ]
 [ 0.28328584 -0.94294085 -0.15484662]]
[[0.43365185]
 [0.56167978]]
[[ 1.19512638 -0.72113129 -0.04956085]
 [ 0.84496562 -0.38126107  0.40683316]]


In [15]:
c.shape

(2, 3)

In [16]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [17]:
c.shape

(12288, 45)

In [18]:
a = np.random.randn(3, 4) # a.shape = (2, 3)
b = np.random.randn(4, 1) # b.shape = (2, 1)
c = a + b.T
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
c.shape

(3, 4)

In [19]:
a = np.random.randn(3, 4) # a.shape = (2, 3)
b = np.random.randn(4, 1) # b.shape = (2, 1)

c = a + b.T
c.shape

(3, 4)

In [20]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[-1.26083284,  2.22043139, -0.70297023],
       [ 0.06458837, -0.63826941, -0.12345341],
       [ 0.00824921,  0.2606534 , -0.27395855]])